---
- name: install cluster
  hosts: nodes
  gather_facts: no
  become: true
  tasks:
  - name: install packages
    yum:
      name:
        - device-mapper-multipath
        - gfs2-utils
        - iscsi-initiator-utils
        - lvm2-lockd
        - dlm


  - name: start services
    service:

